version: '3.8'

services:
  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: pixelvault-dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env

  # Production service
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pixelvault-prod
    ports:
      - "80:80"
    restart: unless-stopped