import { Request, Response } from 'express';
import { FileService } from '../application/FileService';
import { FileValidator } from '../application/FileValidator';

export class UploadController {
  constructor(private fileService: FileService, private fileValidator: FileValidator) {}

  uploadImage(req: Request, res: Response): void {
    if (!req.file) {
      res.status(400).send('No file uploaded.');
      return;
    }

    if (!this.fileValidator.isValid(req.file)) {
      res.status(400).send(this.fileValidator.getValidationErrorMessage(req.file));
      return;
    }

    // The filename is already generated by multer's diskStorage using FileService
    const imageUrl = `http://localhost:3001/uploads/${req.file.filename}`;
    res.status(200).json({ message: 'File uploaded successfully', imageUrl, filename: req.file.filename });
  }
}
